import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/ui/layouts/Header";
import Popup from "@/ui/components/Popup";
import Toploader from "@/ui/components/Toploader/Toploader";
import { Bounce, toast, ToastContainer } from "react-toastify";
import { ToastProvider } from "@/contexts/ToastProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Quản lý cửa hàng máy tính",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ToastProvider>
          <Toploader />
          <Header />
          <Popup>Cho anh trai C2</Popup>
          <div className="mt-[var(--height-header)] w-[1580px] mx-auto">
            {children}
          </div>
        </ToastProvider>
      </body>
    </html>
  );
}
